import React, { useState } from "react";
import Modal from "../ui/Modal.jsx";
import { Button, Field, inputCls } from "../ui/PageHeader.jsx";
import { CheckCircle2 } from "lucide-react";

export default function PhysicalVerificationModal({ receipt, onSuccess, onClose, verifyPhysicalStock }) {
  const [formData, setFormData] = useState({
    physicalCountConfirmed: false,
    verificationNotes: "",
  });
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.physicalCountConfirmed) {
      alert("You must confirm that the physical count matches the GRN quantity before verifying.");
      return;
    }
    
    setSubmitting(true);
    
    const { ok } = await verifyPhysicalStock(receipt.id, {
      physicalCountConfirmed: formData.physicalCountConfirmed,
      verificationNotes: formData.verificationNotes,
    });
    
    setSubmitting(false);
    if (ok) {
      onSuccess();
    }
  };

  return (
    <Modal open={true} onClose={onClose} title="Verify Physical Stock">
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4 mb-4">
          <div className="text-sm space-y-1">
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">Receipt:</span>
              <span className="font-medium">{receipt.refNo}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">GRN Number:</span>
              <span className="font-medium text-indigo-600 dark:text-indigo-400">
                {receipt.grnNumber}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">Item:</span>
              <span className="font-medium">{receipt.itemName}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">Quantity:</span>
              <span className="font-medium text-lg text-emerald-600 dark:text-emerald-400">
                {receipt.qty} {receipt.unit}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">Bin Location:</span>
              <span className="font-medium">{receipt.bin || "RECEIVING"}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-600 dark:text-slate-400">Generated By:</span>
              <span className="font-medium">{receipt.grnGeneratedByName || "Unknown"}</span>
            </div>
            {receipt.grnGeneratedAt && (
              <div className="flex justify-between">
                <span className="text-slate-600 dark:text-slate-400">Generated On:</span>
                <span className="font-medium">
                  {new Date(receipt.grnGeneratedAt).toLocaleString()}
                </span>
              </div>
            )}
          </div>
        </div>

        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-md p-3">
          <p className="text-xs text-amber-700 dark:text-amber-300">
            <strong>Verify:</strong> Physical count matches GRN quantity ({receipt.qty} {receipt.unit}), bin location correct, item condition acceptable.
          </p>
        </div>

        <Field htmlFor="physicalCountConfirmed">
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              id="physicalCountConfirmed"
              checked={formData.physicalCountConfirmed}
              onChange={(e) =>
                setFormData({ ...formData, physicalCountConfirmed: e.target.checked })
              }
              className="mt-1 w-5 h-5 text-emerald-600 rounded border-slate-300 dark:border-slate-600 focus:ring-emerald-500"
              required
            />
            <span className="text-sm font-medium text-slate-900 dark:text-slate-100">
              I confirm physical count matches GRN quantity *
            </span>
          </label>
        </Field>

        <Field label="Verification Notes *" htmlFor="verificationNotes">
          <textarea
            id="verificationNotes"
            value={formData.verificationNotes}
            onChange={(e) => setFormData({ ...formData, verificationNotes: e.target.value })}
            rows="3"
            className={inputCls}
            placeholder="e.g., Physical stock verified. Matches GRN quantity."
            required
          />
        </Field>

        <div className="bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-md p-3">
          <p className="text-xs text-emerald-700 dark:text-emerald-300">
            <strong>Final Step:</strong> Completes GRN workflow. Stock becomes available for requisitions. PRO & PAO notified.
          </p>
        </div>

        <div className="flex justify-end gap-3 pt-4">
          <Button type="button" onClick={onClose} variant="ghost" disabled={submitting}>
            Cancel
          </Button>
          <Button
            type="submit"
            disabled={submitting || !formData.physicalCountConfirmed}
            className="bg-emerald-600 hover:bg-emerald-700"
          >
            {submitting ? "Verifying..." : "Verify Stock"}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
