import React, { useState, useMemo } from "react";
import { ClipboardCheck } from "lucide-react";
import { useApp } from "../../context/AppContext.jsx";
import { PageHeader, Button } from "../../components/ui/PageHeader.jsx";
import DataTable from "../../components/ui/DataTable.jsx";
import DelegationStatusBadge from "../../components/delegation/DelegationStatusBadge.jsx";
import PhysicalVerificationModal from "../../components/delegation/PhysicalVerificationModal.jsx";

export default function PendingVerifications() {
  const { goodsReceipts, items, verifyPhysicalStock } = useApp();
  const [selectedReceipt, setSelectedReceipt] = useState(null);

  // Filter receipts awaiting Store Head verification
  const pendingVerifications = useMemo(() => {
    return goodsReceipts
      .filter((r) => r.status === "Awaiting Store Head Verification")
      .map((receipt) => {
        // Handle both single-item and multi-item receipts
        const isMultiItem = receipt.totalItems > 0 && receipt.items && receipt.items.length > 0;
        
        let itemName, unit;
        
        if (isMultiItem) {
          // Multi-item receipt: show summary
          const generatedItems = receipt.items.filter(i => i.grnGenerated);
          itemName = generatedItems.length > 0 
            ? `${generatedItems.length} items generated` 
            : `${receipt.items.length} items`;
          unit = "";
        } else {
          // Single-item receipt (backward compatibility)
          const item = items.find((i) => i.id === receipt.itemId);
          itemName = receipt.itemName || item?.name || "Unknown";
          unit = item?.unit || "";
        }
        
        // Keep original qty from receipt - don't override it
        return {
          ...receipt,
          itemName,
          unit,
          isMultiItem,
        };
      })
      .sort((a, b) => new Date(b.grnGeneratedAt) - new Date(a.grnGeneratedAt));
  }, [goodsReceipts, items]);

  const columns = [
    {
      key: "refNo",
      header: "Receipt #",
      render: (row) => (
        <span className="font-medium text-slate-900 dark:text-slate-100">
          {row.refNo}
        </span>
      ),
    },
    {
      key: "grnNumber",
      header: "GRN Number",
      render: (row) => (
        <span className="font-mono text-indigo-600 dark:text-indigo-400 font-medium">
          {row.grnNumber || "N/A"}
        </span>
      ),
    },
    {
      key: "itemName",
      header: "Item",
      render: (row) => (
        <div>
          <div className="font-medium">{row.itemName}</div>
          <div className="text-sm text-slate-500">{row.poReference}</div>
        </div>
      ),
    },
    {
      key: "qty",
      header: "Quantity",
      render: (row) => (
        <span className="font-medium text-lg text-emerald-600 dark:text-emerald-400">
          {row.qty} {row.unit}
        </span>
      ),
    },
    {
      key: "bin",
      header: "Bin Location",
      render: (row) => (
        <span className="font-mono text-sm bg-slate-100 dark:bg-slate-800 px-2 py-1 rounded">
          {row.bin || "RECEIVING"}
        </span>
      ),
    },
    {
      key: "grnGeneratedAt",
      header: "Generated By",
      render: (row) => (
        <div className="text-sm">
          {row.grnGeneratedByName && (
            <div className="text-slate-600 dark:text-slate-400">
              {row.grnGeneratedByName}
            </div>
          )}
          {row.grnGeneratedAt && (
            <div className="text-slate-500 dark:text-slate-500">
              {new Date(row.grnGeneratedAt).toLocaleDateString()}
            </div>
          )}
        </div>
      ),
    },
    {
      key: "status",
      header: "Status",
      render: (row) => <DelegationStatusBadge status={row.status} />,
    },
    {
      key: "id",
      header: "",
      render: (row) => (
        <Button size="sm" onClick={() => setSelectedReceipt(row)}>
          Verify Stock
        </Button>
      ),
    },
  ];

  const handleVerificationSuccess = () => {
    setSelectedReceipt(null);
  };

  return (
    <div>
      <PageHeader
        title="Pending Verifications"
        icon={ClipboardCheck}
        description="Verify physical stock matches GRN quantities"
      />

      {pendingVerifications.length === 0 ? (
        <div className="text-center py-12 bg-slate-50 dark:bg-slate-800/50 rounded-lg">
          <ClipboardCheck className="w-12 h-12 mx-auto text-slate-400 mb-3" />
          <p className="text-slate-600 dark:text-slate-400">
            No verifications pending
          </p>
          <p className="text-sm text-slate-500 dark:text-slate-500 mt-1">
            GRNs generated by Stock Clerks will appear here for your verification
          </p>
        </div>
      ) : (
        <DataTable
          columns={columns}
          rows={pendingVerifications}
          searchKeys={["refNo", "grnNumber", "itemName", "poReference"]}
        />
      )}

      {selectedReceipt && (
        <PhysicalVerificationModal
          receipt={selectedReceipt}
          onSuccess={handleVerificationSuccess}
          onClose={() => setSelectedReceipt(null)}
          verifyPhysicalStock={verifyPhysicalStock}
        />
      )}
    </div>
  );
}
